version: "3.9"

services:
  nodejs:
    build:
      context: .
      dockerfile: Dockerfile
    image: nodejs
    container_name: nodejs
    restart: unless-stopped
    ports:
      - "8800:8800"
    volumes:
      - ./src:/home/node/app
      - node_modules:/home/node/app/node_modules

volumes:
  node_modules:
